"""Update passwords column

Revision ID: 61df62bd9239
Revises: 62914a6df7df
Create Date: 2019-02-12 16:36:56.353320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61df62bd9239'
down_revision = '62914a6df7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
